version: "3.7"

services:
    nginx:
        container_name: nginx_backendml
        image: nginx:alpine
        depends_on:
            - fastapi
        ports:
            - 8082:80
        volumes:
            - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - custom

    fastapi:
        container_name: fastapi_backendml
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8001:8000
        networks:
            - custom
        depends_on:
            db:
                condition: service_healthy
        command:
            - "sh"
            - "-c"
            - "alembic upgrade head && python3 src/main.py"

    db:
        container_name: postgres_backendml
        image: postgres:13.0-alpine
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_DB=${POSTGRES_DB}
        networks:
            - custom
        ports:
            - "2344:${POSTGRES_PORT}"
        depends_on:
            - redis
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5

    redis:
        container_name: redis_backendml
        image: redis:alpine
        networks:
            - custom
        ports:
            - "6380:6379"

networks:
    custom:
        driver: bridge